FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBUG=1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
        build-essential \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements-dev.txt /app/
RUN pip install --no-cache-dir -r requirements-dev.txt

# Copy project
COPY . /app/

# Create the necessary directories
RUN mkdir -p /app/logs /app/media /app/staticfiles

# Collect static files
RUN python lms_platform/manage.py collectstatic --noinput

# Expose port
EXPOSE 8000

# Run the application
CMD ["python", "lms_platform/manage.py", "runserver", "0.0.0.0:8000"]
